- name: Check for existing bottle on release
        id: check_bottle
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          FORMULA_NAME="mpv-lgpl"
          FORMULA_FILE="mpv-lgpl.rb"

          FORMULA_VERSION=$(grep 'url' "$FORMULA_FILE" | grep -o 'mpv-.*\.tar\.[gx]z' | sed 's/mpv-//' | sed 's/\.tar\..*//')
          FORMULA_REVISION=$(grep -E '^\s*revision\s+' "$FORMULA_FILE" | awk '{print $2}')

          if [[ -z "$FORMULA_REVISION" ]]; then
            FORMULA_REVISION="0"
          fi

          if [ "$FORMULA_REVISION" == "0" ]; then
            RELEASE_TAG="v$FORMULA_VERSION"
          else
            RELEASE_TAG="v${FORMULA_VERSION}_${FORMULA_REVISION}"
          fi

          OS_VERSION="${{ matrix.os }}"
          if [ "$OS_VERSION" == "macos-15" ]; then
            OS_TAG="sequoia"
          elif [ "$OS_VERSION" == "macos-14" ]; then
            OS_TAG="sonoma"
          elif [ "$OS_VERSION" == "macos-13" ]; then
            OS_TAG="ventura"
          else
            OS_TAG=$(echo "$OS_VERSION" | sed 's/macos-//')
          fi

          ARCH_TAG="${{ matrix.arch }}"

          if [ "$ARCH_TAG" == "arm64" ]; then
              ARCH_PREFIX="${ARCH_TAG}_"
          else
              ARCH_PREFIX=""
          fi

          FILE_NAME="${FORMULA_NAME}-${FORMULA_VERSION}_${FORMULA_REVISION}.${ARCH_PREFIX}${OS_TAG}.bottle.tar.gz"
          FILE_NAME=$(echo "$FILE_NAME" | sed 's/--/-/g')

          echo "Expected file: $FILE_NAME"

          RELEASE_ASSETS=$(gh release view "$RELEASE_TAG" --json assets 2>/dev/null || true)

          if [[ "$RELEASE_ASSETS" == *"$FILE_NAME"* ]]; then
            echo "skip=true" >> "$GITHUB_OUTPUT"
            echo "--- Bottle for this configuration already exists. Skipping build and upload. ---"
          else
            echo "skip=false" >> "$GITHUB_OUTPUT"
            echo "--- Bottle does not exist. Proceeding with build. ---"
          fi
