name: "Release Bottles"

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-release:
    strategy:
      matrix:
        os: [macos-15, macos-14, macos-13]
        arch: [arm64, x86_64]
        exclude:
          - os: macos-15
            arch: x86_64
      fail-fast: false
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check for existing bottle on release
        id: check_bottle
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          FORMULA_NAME="mpv-lgpl"
          FORMULA_FILE="mpv-lgpl.rb"
          
          if [ ! -f "$FORMULA_FILE" ]; then
            echo "::error::Formula file '$FORMULA_FILE' not found."
            exit 1
          fi

          # `bottle do`ブロックの`root_url`からバージョンとリビジョンをまとめて抽出
          FORMULA_TAG=$(grep 'root_url ' "$FORMULA_FILE" | grep -o 'v[0-9.]*_[0-9.]*' | sed 's/^v//' | tr -d '\n' || true)
          if [[ -z "$FORMULA_TAG" ]]; then
            echo "::error::Could not determine formula tag from 'root_url'. Aborting."
            exit 1
          fi
          
          # 抽出したタグからバージョンとリビジョンを分離
          FORMULA_VERSION=$(echo "$FORMULA_TAG" | cut -d'_' -f1)
          FORMULA_REVISION=$(echo "$FORMULA_TAG" | cut -d'_' -f2)
          
          # リリースタグを生成
          RELEASE_TAG="v${FORMULA_VERSION}_${FORMULA_REVISION}"
          
          OS_VERSION="${{ matrix.os }}"
          if [ "$OS_VERSION" == "macos-15" ]; then
            OS_TAG="sequoia"
          elif [ "$OS_VERSION" == "macos-14" ]; then
            OS_TAG="sonoma"
          elif [ "$OS_VERSION" == "macos-13" ]; then
            OS_TAG="ventura"
          else
            OS_TAG=$(echo "$OS_VERSION" | sed 's/macos-//')
          fi

          ARCH_TAG="${{ matrix.arch }}"

          if [ "$ARCH_TAG" == "arm64" ]; then
              ARCH_PREFIX="${ARCH_TAG}_"
          else
              ARCH_PREFIX=""
          fi
          
          # ファイル名を生成
          FILE_NAME="${FORMULA_NAME}-${FORMULA_VERSION}_${FORMULA_REVISION}.${ARCH_PREFIX}${OS_TAG}.bottle.tar.gz"
          FILE_NAME=$(echo "$FILE_NAME" | sed 's/--/-/g')
          
          echo "Expected file: $FILE_NAME"
          echo "Expected release tag: $RELEASE_TAG"
          
          RELEASE_ASSETS=$(gh release view "$RELEASE_TAG" --json assets 2>/dev/null || true)
          
          if [[ "$RELEASE_ASSETS" == *"$FILE_NAME"* ]]; then
            echo "skip=true" >> "$GITHUB_OUTPUT"
            echo "--- Bottle for this configuration already exists. Skipping build and upload. ---"
          else
            echo "skip=false" >> "$GITHUB_OUTPUT"
            echo "--- Bottle does not exist. Proceeding with build. ---"
          fi
