name: "Release Bottles"

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-release:
    strategy:
      matrix:
        os: [macos-15, macos-14, macos-13]
        arch: [arm64, x86_64]
        exclude:
          - os: macos-15
            arch: x86_64
      fail-fast: false
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check for existing bottle on release
        id: check_bottle
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          FORMULA_NAME="mpv-lgpl"
          FORMULA_FILE="mpv-lgpl.rb"
          
          if [ ! -f "$FORMULA_FILE" ]; then
            echo "::error::Formula file '$FORMULA_FILE' not found."
            exit 1
          fi

          # Homebrewのurlからバージョン番号を正確に抽出
          FORMULA_VERSION=$(grep 'url' "$FORMULA_FILE" | sed -E 's/.*v([0-9.]*)\.tar\.gz.*/\1/' | tr -d '\n' || true)
          if [[ -z "$FORMULA_VERSION" ]]; then
            echo "::warning::Could not determine formula version. Using fallback."
            FORMULA_VERSION="0.40.0"
          fi
          
          # Homebrewのrevisionからリビジョン番号を正確に抽出
          FORMULA_REVISION=$(grep -E '^\s*revision\s+[0-9]+' "$FORMULA_FILE" | awk '{print $2}' | tr -d '\n' || true)
          if [[ -z "$FORMULA_REVISION" ]]; then
            FORMULA_REVISION="0"
          fi
          
          # リリースタグを生成
          if [ "$FORMULA_REVISION" == "0" ]; then
            RELEASE_TAG="v$FORMULA_VERSION"
          else
            RELEASE_TAG="v${FORMULA_VERSION}_${FORMULA_REVISION}"
          fi
          
          OS_VERSION="${{ matrix.os }}"
          if [ "$OS_VERSION" == "macos-15" ]; then
            OS_TAG="sequoia"
          elif [ "$OS_VERSION" == "macos-14" ]; then
            OS_TAG="sonoma"
          elif [ "$OS_VERSION" == "macos-13" ]; then
            OS_TAG="ventura"
          else
            OS_TAG=$(echo "$OS_VERSION" | sed 's/macos-//')
          fi

          ARCH_TAG="${{ matrix.arch }}"

          if [ "$ARCH_TAG" == "arm64" ]; then
              ARCH_PREFIX="${ARCH_TAG}_"
          else
              ARCH_PREFIX=""
          fi
          
          # ファイル名を生成。リビジョンが0の場合は'_0'を含めない。
          if [ "$FORMULA_REVISION" == "0" ]; then
            FILE_NAME="${FORMULA_NAME}-${FORMULA_VERSION}.${ARCH_PREFIX}${OS_TAG}.bottle.tar.gz"
          else
            FILE_NAME="${FORMULA_NAME}-${FORMULA_VERSION}_${FORMULA_REVISION}.${ARCH_PREFIX}${OS_TAG}.bottle.tar.gz"
          fi
          
          FILE_NAME=$(echo "$FILE_NAME" | sed 's/--/-/g')
          
          echo "Expected file: $FILE_NAME"
          echo "Expected release tag: $RELEASE_TAG"
          
          RELEASE_ASSETS=$(gh release view "$RELEASE_TAG" --json assets 2>/dev/null || true)
          
          if [[ "$RELEASE_ASSETS" == *"$FILE_NAME"* ]]; then
            echo "skip=true" >> "$GITHUB_OUTPUT"
            echo "--- Bottle for this configuration already exists. Skipping build and upload. ---"
          else
            echo "skip=false" >> "$GITHUB_OUTPUT"
            echo "--- Bottle does not exist. Proceeding with build. ---"
          fi


          
          gh release upload "$RELEASE_TAG" \
            "${{ steps.bottle.outputs.BOTTLE_FILENAME }}" \
            "${{ steps.bottle.outputs.JSON_FILENAME }}" \
            --clobber
